# ===================================
# Filter Scope Definitions
# ===================================
scopes:

    published:

        # Filter name
        label: Published

        # Filter type
        type: checkbox

        # SQL Conditions
        conditions: published <> 1